input_path: "${projectDir}/../mop_preprocess/outfolder/"
comparison: "${projectDir}/comparison.tsv"

reference: "${projectDir}/../anno/yeast_rRNA_ref.fa.gz"
output: "${projectDir}/output_mod"
pars_tools: "${projectDir}/tools_opt.tsv"

# flows
epinano: "YES"
nanocompore: "NO"
tombo_lsc: "YES"
tombo_msc: "YES"
modphred: "NO"

# epinano plots
epinano_plots: "YES"
email: ""
