input_path: "${projectDir}/../mop_preprocess/outfolder/"
reference: "${projectDir}/../anno/yeast_rRNA_ref.fa.gz"
    
pars_tools: "${projectDir}/tools_opt.tsv"

output: "${projectDir}/outputPoly"

tailfindr: "YES"

# Different modes: standard, n3ps_r9 or n3ps_r10
tailfindr_mode: "standard"

nanopolish: "YES"
 
email: "yourname@yourdomain"
