input_path: "${projectDir}/../mop_preprocess/output/"
reference: "${projectDir}/../anno/yeast_rRNA_ref.fa.gz"
    
pars_tools: "${projectDir}/tools_opt.tsv"

output: "${projectDir}/outputPoly"

tailfindr: "YES"
tailfindr_mode: "standard"

nanopolish: "YES"
 
email: "yourname@yourdomain"
