name: mop3-CI
# When this workflow is triggered
on: 
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    name: mop3 ci
    # This job runs on Linux
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        java_version: [11]

    steps:
     - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # when set to "true" but frees about 6 GB
        tool-cache: true

      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v3
        with:
         token: ${{ github.token }}
         repository: biocorecrg/MoP3
         fetch-depth: 1
         submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
         java-version: ${{ matrix.java_version }}
         distribution: 'adopt'
         architecture: x64
        
      - name: MOP3
        run: |
          curl -fsSL get.nextflow.io | bash
          bash INSTALL.sh
          cd mop_preprocess
          ../nextflow run mop_preprocess.nf -params-file params.f5.yaml -with-docker -profile ci
          rm -rf work
          cd ../mop_mod
          ../nextflow run mop_mod.nf -params-file params.yaml -with-docker -profile ci
          rm -rf work
          cd ../mop_tail
           ../nextflow run mop_tail.nf -with-docker  -params-file params.yaml -profile ci

        env:
          NXF_ANSI_LOG: false
