name: mop3-CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: mop3 ci
    # This job runs on Linux
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        java_version: ['11.0.4']

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 1
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
          architecture: x64

      - name: MOP3
        run: |
          curl -fsSL get.nextflow.io | bash
          # Install Master Of Pores 3
          #git clone --depth 1 --recurse-submodules https://${{ secrets.GIT_TOKEN }}:x-oauth-basic@github.com/biocorecrg/MoP3.git
          git clone --depth 1 --recurse-submodules https://{TOKEN}/github.com/biocorecrg/MoP3.git
          cd MoP3
          bash INSTALL.sh
          cd mop_preprocess 
          ../../nextflow run mop_preprocess.nf -with-docker -profile local
          cd ../mop_mod
          ../../nextflow run mop_mod.nf -with-docker -profile local
          cd ../mop_tail
           ../../nextflow run mop_tail.nf -with-docker -profile local

        env:
          NXF_ANSI_LOG: false
